#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD4006SFileGenerator.SMSData
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="T200EXTRACTS")]
	public partial class T200EXTRACTSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSTU_YRQ_M(STU_YRQ_M instance);
    partial void UpdateSTU_YRQ_M(STU_YRQ_M instance);
    partial void DeleteSTU_YRQ_M(STU_YRQ_M instance);
    partial void InsertSTU_D(STU_D instance);
    partial void UpdateSTU_D(STU_D instance);
    partial void DeleteSTU_D(STU_D instance);
    partial void InsertYRQ_M(YRQ_M instance);
    partial void UpdateYRQ_M(YRQ_M instance);
    partial void DeleteYRQ_M(YRQ_M instance);
    #endregion
		
		public T200EXTRACTSDataContext() : 
				base(global::SD4006SFileGenerator.Properties.Settings.Default.T200EXTRACTSConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public T200EXTRACTSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public T200EXTRACTSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public T200EXTRACTSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public T200EXTRACTSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<STU_YRQ_M> STU_YRQ_Ms
		{
			get
			{
				return this.GetTable<STU_YRQ_M>();
			}
		}
		
		public System.Data.Linq.Table<STU_D> STU_Ds
		{
			get
			{
				return this.GetTable<STU_D>();
			}
		}
		
		public System.Data.Linq.Table<YRQ_M> YRQ_Ms
		{
			get
			{
				return this.GetTable<YRQ_M>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.STU_YRQ_M")]
	public partial class STU_YRQ_M : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IMAGE_RECNBR;
		
		private string _SQ_SID;
		
		private string _SQ_YRQ;
		
		private System.Nullable<char> _ATTND_NEXT_QTR;
		
		private string _CITZ_STAT;
		
		private System.Nullable<decimal> _CONCURR_ENR;
		
		private string _FEE_PAY_STAT;
		
		private System.Nullable<decimal> _QTR_CR_EARN;
		
		private System.Nullable<decimal> _QTR_CR_REG;
		
		private System.Nullable<decimal> _QTR_GPA;
		
		private System.Nullable<decimal> _QTR_GPA_CR;
		
		private System.Nullable<System.DateTime> _REG_ACTV_DATE;
		
		private System.Nullable<char> _RES_STAT;
		
		private System.Nullable<char> _STU_INT;
		
		private System.Nullable<char> _STU_TYP;
		
		private string _STU_PRG_ENR;
		
		private System.Nullable<char> _VET_BENE;
		
		private string _CONS_QTR;
		
		private string _STU_PURP_ATTND;
		
		private string _STU_PLAN_WORK;
		
		private System.Nullable<decimal> _QTR_HR_EARN;
		
		private System.Nullable<decimal> _QTR_HR_REG;
		
		private System.Nullable<decimal> _QTR_GPA_HR;
		
		private System.Nullable<char> _STU_QTR_STAT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIMAGE_RECNBRChanging(int value);
    partial void OnIMAGE_RECNBRChanged();
    partial void OnSQ_SIDChanging(string value);
    partial void OnSQ_SIDChanged();
    partial void OnSQ_YRQChanging(string value);
    partial void OnSQ_YRQChanged();
    partial void OnATTND_NEXT_QTRChanging(System.Nullable<char> value);
    partial void OnATTND_NEXT_QTRChanged();
    partial void OnCITZ_STATChanging(string value);
    partial void OnCITZ_STATChanged();
    partial void OnCONCURR_ENRChanging(System.Nullable<decimal> value);
    partial void OnCONCURR_ENRChanged();
    partial void OnFEE_PAY_STATChanging(string value);
    partial void OnFEE_PAY_STATChanged();
    partial void OnQTR_CR_EARNChanging(System.Nullable<decimal> value);
    partial void OnQTR_CR_EARNChanged();
    partial void OnQTR_CR_REGChanging(System.Nullable<decimal> value);
    partial void OnQTR_CR_REGChanged();
    partial void OnQTR_GPAChanging(System.Nullable<decimal> value);
    partial void OnQTR_GPAChanged();
    partial void OnQTR_GPA_CRChanging(System.Nullable<decimal> value);
    partial void OnQTR_GPA_CRChanged();
    partial void OnREG_ACTV_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnREG_ACTV_DATEChanged();
    partial void OnRES_STATChanging(System.Nullable<char> value);
    partial void OnRES_STATChanged();
    partial void OnSTU_INTChanging(System.Nullable<char> value);
    partial void OnSTU_INTChanged();
    partial void OnSTU_TYPChanging(System.Nullable<char> value);
    partial void OnSTU_TYPChanged();
    partial void OnSTU_PRG_ENRChanging(string value);
    partial void OnSTU_PRG_ENRChanged();
    partial void OnVET_BENEChanging(System.Nullable<char> value);
    partial void OnVET_BENEChanged();
    partial void OnCONS_QTRChanging(string value);
    partial void OnCONS_QTRChanged();
    partial void OnSTU_PURP_ATTNDChanging(string value);
    partial void OnSTU_PURP_ATTNDChanged();
    partial void OnSTU_PLAN_WORKChanging(string value);
    partial void OnSTU_PLAN_WORKChanged();
    partial void OnQTR_HR_EARNChanging(System.Nullable<decimal> value);
    partial void OnQTR_HR_EARNChanged();
    partial void OnQTR_HR_REGChanging(System.Nullable<decimal> value);
    partial void OnQTR_HR_REGChanged();
    partial void OnQTR_GPA_HRChanging(System.Nullable<decimal> value);
    partial void OnQTR_GPA_HRChanged();
    partial void OnSTU_QTR_STATChanging(System.Nullable<char> value);
    partial void OnSTU_QTR_STATChanged();
    #endregion
		
		public STU_YRQ_M()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMAGE_RECNBR", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int IMAGE_RECNBR
		{
			get
			{
				return this._IMAGE_RECNBR;
			}
			set
			{
				if ((this._IMAGE_RECNBR != value))
				{
					this.OnIMAGE_RECNBRChanging(value);
					this.SendPropertyChanging();
					this._IMAGE_RECNBR = value;
					this.SendPropertyChanged("IMAGE_RECNBR");
					this.OnIMAGE_RECNBRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SQ_SID", DbType="Char(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SQ_SID
		{
			get
			{
				return this._SQ_SID;
			}
			set
			{
				if ((this._SQ_SID != value))
				{
					this.OnSQ_SIDChanging(value);
					this.SendPropertyChanging();
					this._SQ_SID = value;
					this.SendPropertyChanged("SQ_SID");
					this.OnSQ_SIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SQ_YRQ", DbType="Char(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SQ_YRQ
		{
			get
			{
				return this._SQ_YRQ;
			}
			set
			{
				if ((this._SQ_YRQ != value))
				{
					this.OnSQ_YRQChanging(value);
					this.SendPropertyChanging();
					this._SQ_YRQ = value;
					this.SendPropertyChanged("SQ_YRQ");
					this.OnSQ_YRQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ATTND_NEXT_QTR", DbType="Char(1)")]
		public System.Nullable<char> ATTND_NEXT_QTR
		{
			get
			{
				return this._ATTND_NEXT_QTR;
			}
			set
			{
				if ((this._ATTND_NEXT_QTR != value))
				{
					this.OnATTND_NEXT_QTRChanging(value);
					this.SendPropertyChanging();
					this._ATTND_NEXT_QTR = value;
					this.SendPropertyChanged("ATTND_NEXT_QTR");
					this.OnATTND_NEXT_QTRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITZ_STAT", DbType="Char(2)")]
		public string CITZ_STAT
		{
			get
			{
				return this._CITZ_STAT;
			}
			set
			{
				if ((this._CITZ_STAT != value))
				{
					this.OnCITZ_STATChanging(value);
					this.SendPropertyChanging();
					this._CITZ_STAT = value;
					this.SendPropertyChanged("CITZ_STAT");
					this.OnCITZ_STATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONCURR_ENR", DbType="Decimal(3,0)")]
		public System.Nullable<decimal> CONCURR_ENR
		{
			get
			{
				return this._CONCURR_ENR;
			}
			set
			{
				if ((this._CONCURR_ENR != value))
				{
					this.OnCONCURR_ENRChanging(value);
					this.SendPropertyChanging();
					this._CONCURR_ENR = value;
					this.SendPropertyChanged("CONCURR_ENR");
					this.OnCONCURR_ENRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FEE_PAY_STAT", DbType="Char(2)")]
		public string FEE_PAY_STAT
		{
			get
			{
				return this._FEE_PAY_STAT;
			}
			set
			{
				if ((this._FEE_PAY_STAT != value))
				{
					this.OnFEE_PAY_STATChanging(value);
					this.SendPropertyChanging();
					this._FEE_PAY_STAT = value;
					this.SendPropertyChanged("FEE_PAY_STAT");
					this.OnFEE_PAY_STATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTR_CR_EARN", DbType="Decimal(4,1)")]
		public System.Nullable<decimal> QTR_CR_EARN
		{
			get
			{
				return this._QTR_CR_EARN;
			}
			set
			{
				if ((this._QTR_CR_EARN != value))
				{
					this.OnQTR_CR_EARNChanging(value);
					this.SendPropertyChanging();
					this._QTR_CR_EARN = value;
					this.SendPropertyChanged("QTR_CR_EARN");
					this.OnQTR_CR_EARNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTR_CR_REG", DbType="Decimal(4,1)")]
		public System.Nullable<decimal> QTR_CR_REG
		{
			get
			{
				return this._QTR_CR_REG;
			}
			set
			{
				if ((this._QTR_CR_REG != value))
				{
					this.OnQTR_CR_REGChanging(value);
					this.SendPropertyChanging();
					this._QTR_CR_REG = value;
					this.SendPropertyChanged("QTR_CR_REG");
					this.OnQTR_CR_REGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTR_GPA", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> QTR_GPA
		{
			get
			{
				return this._QTR_GPA;
			}
			set
			{
				if ((this._QTR_GPA != value))
				{
					this.OnQTR_GPAChanging(value);
					this.SendPropertyChanging();
					this._QTR_GPA = value;
					this.SendPropertyChanged("QTR_GPA");
					this.OnQTR_GPAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTR_GPA_CR", DbType="Decimal(4,1)")]
		public System.Nullable<decimal> QTR_GPA_CR
		{
			get
			{
				return this._QTR_GPA_CR;
			}
			set
			{
				if ((this._QTR_GPA_CR != value))
				{
					this.OnQTR_GPA_CRChanging(value);
					this.SendPropertyChanging();
					this._QTR_GPA_CR = value;
					this.SendPropertyChanged("QTR_GPA_CR");
					this.OnQTR_GPA_CRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REG_ACTV_DATE", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> REG_ACTV_DATE
		{
			get
			{
				return this._REG_ACTV_DATE;
			}
			set
			{
				if ((this._REG_ACTV_DATE != value))
				{
					this.OnREG_ACTV_DATEChanging(value);
					this.SendPropertyChanging();
					this._REG_ACTV_DATE = value;
					this.SendPropertyChanged("REG_ACTV_DATE");
					this.OnREG_ACTV_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RES_STAT", DbType="Char(1)")]
		public System.Nullable<char> RES_STAT
		{
			get
			{
				return this._RES_STAT;
			}
			set
			{
				if ((this._RES_STAT != value))
				{
					this.OnRES_STATChanging(value);
					this.SendPropertyChanging();
					this._RES_STAT = value;
					this.SendPropertyChanged("RES_STAT");
					this.OnRES_STATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STU_INT", DbType="Char(1)")]
		public System.Nullable<char> STU_INT
		{
			get
			{
				return this._STU_INT;
			}
			set
			{
				if ((this._STU_INT != value))
				{
					this.OnSTU_INTChanging(value);
					this.SendPropertyChanging();
					this._STU_INT = value;
					this.SendPropertyChanged("STU_INT");
					this.OnSTU_INTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STU_TYP", DbType="Char(1)")]
		public System.Nullable<char> STU_TYP
		{
			get
			{
				return this._STU_TYP;
			}
			set
			{
				if ((this._STU_TYP != value))
				{
					this.OnSTU_TYPChanging(value);
					this.SendPropertyChanging();
					this._STU_TYP = value;
					this.SendPropertyChanged("STU_TYP");
					this.OnSTU_TYPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STU_PRG_ENR", DbType="Char(4)")]
		public string STU_PRG_ENR
		{
			get
			{
				return this._STU_PRG_ENR;
			}
			set
			{
				if ((this._STU_PRG_ENR != value))
				{
					this.OnSTU_PRG_ENRChanging(value);
					this.SendPropertyChanging();
					this._STU_PRG_ENR = value;
					this.SendPropertyChanged("STU_PRG_ENR");
					this.OnSTU_PRG_ENRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VET_BENE", DbType="Char(1)")]
		public System.Nullable<char> VET_BENE
		{
			get
			{
				return this._VET_BENE;
			}
			set
			{
				if ((this._VET_BENE != value))
				{
					this.OnVET_BENEChanging(value);
					this.SendPropertyChanging();
					this._VET_BENE = value;
					this.SendPropertyChanged("VET_BENE");
					this.OnVET_BENEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONS_QTR", DbType="Char(2)")]
		public string CONS_QTR
		{
			get
			{
				return this._CONS_QTR;
			}
			set
			{
				if ((this._CONS_QTR != value))
				{
					this.OnCONS_QTRChanging(value);
					this.SendPropertyChanging();
					this._CONS_QTR = value;
					this.SendPropertyChanged("CONS_QTR");
					this.OnCONS_QTRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STU_PURP_ATTND", DbType="Char(2)")]
		public string STU_PURP_ATTND
		{
			get
			{
				return this._STU_PURP_ATTND;
			}
			set
			{
				if ((this._STU_PURP_ATTND != value))
				{
					this.OnSTU_PURP_ATTNDChanging(value);
					this.SendPropertyChanging();
					this._STU_PURP_ATTND = value;
					this.SendPropertyChanged("STU_PURP_ATTND");
					this.OnSTU_PURP_ATTNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STU_PLAN_WORK", DbType="Char(2)")]
		public string STU_PLAN_WORK
		{
			get
			{
				return this._STU_PLAN_WORK;
			}
			set
			{
				if ((this._STU_PLAN_WORK != value))
				{
					this.OnSTU_PLAN_WORKChanging(value);
					this.SendPropertyChanging();
					this._STU_PLAN_WORK = value;
					this.SendPropertyChanged("STU_PLAN_WORK");
					this.OnSTU_PLAN_WORKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTR_HR_EARN", DbType="Decimal(5,1)")]
		public System.Nullable<decimal> QTR_HR_EARN
		{
			get
			{
				return this._QTR_HR_EARN;
			}
			set
			{
				if ((this._QTR_HR_EARN != value))
				{
					this.OnQTR_HR_EARNChanging(value);
					this.SendPropertyChanging();
					this._QTR_HR_EARN = value;
					this.SendPropertyChanged("QTR_HR_EARN");
					this.OnQTR_HR_EARNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTR_HR_REG", DbType="Decimal(5,1)")]
		public System.Nullable<decimal> QTR_HR_REG
		{
			get
			{
				return this._QTR_HR_REG;
			}
			set
			{
				if ((this._QTR_HR_REG != value))
				{
					this.OnQTR_HR_REGChanging(value);
					this.SendPropertyChanging();
					this._QTR_HR_REG = value;
					this.SendPropertyChanged("QTR_HR_REG");
					this.OnQTR_HR_REGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTR_GPA_HR", DbType="Decimal(5,1)")]
		public System.Nullable<decimal> QTR_GPA_HR
		{
			get
			{
				return this._QTR_GPA_HR;
			}
			set
			{
				if ((this._QTR_GPA_HR != value))
				{
					this.OnQTR_GPA_HRChanging(value);
					this.SendPropertyChanging();
					this._QTR_GPA_HR = value;
					this.SendPropertyChanged("QTR_GPA_HR");
					this.OnQTR_GPA_HRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STU_QTR_STAT", DbType="Char(1)")]
		public System.Nullable<char> STU_QTR_STAT
		{
			get
			{
				return this._STU_QTR_STAT;
			}
			set
			{
				if ((this._STU_QTR_STAT != value))
				{
					this.OnSTU_QTR_STATChanging(value);
					this.SendPropertyChanging();
					this._STU_QTR_STAT = value;
					this.SendPropertyChanged("STU_QTR_STAT");
					this.OnSTU_QTR_STATChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.STU_D")]
	public partial class STU_D : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IMAGE_RECNBR;
		
		private string _ABBR_LAST_NAME;
		
		private string _ADV_ID;
		
		private System.Nullable<System.DateTime> _BIRTH_DATE;
		
		private string _CITZ_STAT;
		
		private string _FEE_PAY_STAT;
		
		private string _LAST_YRQ_ATTND;
		
		private string _STU_CITY;
		
		private string _STU_ST;
		
		private string _STU_STREET;
		
		private string _STU_ZIP;
		
		private System.Nullable<char> _OPT_1;
		
		private System.Nullable<char> _OPT_2;
		
		private System.Nullable<char> _RES_STAT;
		
		private System.Nullable<char> _GENDER;
		
		private string _SID;
		
		private string _STU_DAY_PHONE;
		
		private System.Nullable<char> _STU_ENR_STAT;
		
		private string _STU_EVE_PHONE;
		
		private string _STU_NAME;
		
		private System.Nullable<char> _STU_TYP;
		
		private System.Nullable<char> _VET_BENE;
		
		private string _BAD_ADDR_CD;
		
		private System.Nullable<char> _STU_INT;
		
		private string _STU_PRG_ENR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIMAGE_RECNBRChanging(int value);
    partial void OnIMAGE_RECNBRChanged();
    partial void OnABBR_LAST_NAMEChanging(string value);
    partial void OnABBR_LAST_NAMEChanged();
    partial void OnADV_IDChanging(string value);
    partial void OnADV_IDChanged();
    partial void OnBIRTH_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnBIRTH_DATEChanged();
    partial void OnCITZ_STATChanging(string value);
    partial void OnCITZ_STATChanged();
    partial void OnFEE_PAY_STATChanging(string value);
    partial void OnFEE_PAY_STATChanged();
    partial void OnLAST_YRQ_ATTNDChanging(string value);
    partial void OnLAST_YRQ_ATTNDChanged();
    partial void OnSTU_CITYChanging(string value);
    partial void OnSTU_CITYChanged();
    partial void OnSTU_STChanging(string value);
    partial void OnSTU_STChanged();
    partial void OnSTU_STREETChanging(string value);
    partial void OnSTU_STREETChanged();
    partial void OnSTU_ZIPChanging(string value);
    partial void OnSTU_ZIPChanged();
    partial void OnOPT_1Changing(System.Nullable<char> value);
    partial void OnOPT_1Changed();
    partial void OnOPT_2Changing(System.Nullable<char> value);
    partial void OnOPT_2Changed();
    partial void OnRES_STATChanging(System.Nullable<char> value);
    partial void OnRES_STATChanged();
    partial void OnGENDERChanging(System.Nullable<char> value);
    partial void OnGENDERChanged();
    partial void OnSIDChanging(string value);
    partial void OnSIDChanged();
    partial void OnSTU_DAY_PHONEChanging(string value);
    partial void OnSTU_DAY_PHONEChanged();
    partial void OnSTU_ENR_STATChanging(System.Nullable<char> value);
    partial void OnSTU_ENR_STATChanged();
    partial void OnSTU_EVE_PHONEChanging(string value);
    partial void OnSTU_EVE_PHONEChanged();
    partial void OnSTU_NAMEChanging(string value);
    partial void OnSTU_NAMEChanged();
    partial void OnSTU_TYPChanging(System.Nullable<char> value);
    partial void OnSTU_TYPChanged();
    partial void OnVET_BENEChanging(System.Nullable<char> value);
    partial void OnVET_BENEChanged();
    partial void OnBAD_ADDR_CDChanging(string value);
    partial void OnBAD_ADDR_CDChanged();
    partial void OnSTU_INTChanging(System.Nullable<char> value);
    partial void OnSTU_INTChanged();
    partial void OnSTU_PRG_ENRChanging(string value);
    partial void OnSTU_PRG_ENRChanged();
    #endregion
		
		public STU_D()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMAGE_RECNBR", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int IMAGE_RECNBR
		{
			get
			{
				return this._IMAGE_RECNBR;
			}
			set
			{
				if ((this._IMAGE_RECNBR != value))
				{
					this.OnIMAGE_RECNBRChanging(value);
					this.SendPropertyChanging();
					this._IMAGE_RECNBR = value;
					this.SendPropertyChanged("IMAGE_RECNBR");
					this.OnIMAGE_RECNBRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ABBR_LAST_NAME", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string ABBR_LAST_NAME
		{
			get
			{
				return this._ABBR_LAST_NAME;
			}
			set
			{
				if ((this._ABBR_LAST_NAME != value))
				{
					this.OnABBR_LAST_NAMEChanging(value);
					this.SendPropertyChanging();
					this._ABBR_LAST_NAME = value;
					this.SendPropertyChanged("ABBR_LAST_NAME");
					this.OnABBR_LAST_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADV_ID", DbType="Char(4)")]
		public string ADV_ID
		{
			get
			{
				return this._ADV_ID;
			}
			set
			{
				if ((this._ADV_ID != value))
				{
					this.OnADV_IDChanging(value);
					this.SendPropertyChanging();
					this._ADV_ID = value;
					this.SendPropertyChanged("ADV_ID");
					this.OnADV_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIRTH_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> BIRTH_DATE
		{
			get
			{
				return this._BIRTH_DATE;
			}
			set
			{
				if ((this._BIRTH_DATE != value))
				{
					this.OnBIRTH_DATEChanging(value);
					this.SendPropertyChanging();
					this._BIRTH_DATE = value;
					this.SendPropertyChanged("BIRTH_DATE");
					this.OnBIRTH_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITZ_STAT", DbType="Char(2)")]
		public string CITZ_STAT
		{
			get
			{
				return this._CITZ_STAT;
			}
			set
			{
				if ((this._CITZ_STAT != value))
				{
					this.OnCITZ_STATChanging(value);
					this.SendPropertyChanging();
					this._CITZ_STAT = value;
					this.SendPropertyChanged("CITZ_STAT");
					this.OnCITZ_STATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FEE_PAY_STAT", DbType="Char(2)")]
		public string FEE_PAY_STAT
		{
			get
			{
				return this._FEE_PAY_STAT;
			}
			set
			{
				if ((this._FEE_PAY_STAT != value))
				{
					this.OnFEE_PAY_STATChanging(value);
					this.SendPropertyChanging();
					this._FEE_PAY_STAT = value;
					this.SendPropertyChanged("FEE_PAY_STAT");
					this.OnFEE_PAY_STATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_YRQ_ATTND", DbType="Char(4)")]
		public string LAST_YRQ_ATTND
		{
			get
			{
				return this._LAST_YRQ_ATTND;
			}
			set
			{
				if ((this._LAST_YRQ_ATTND != value))
				{
					this.OnLAST_YRQ_ATTNDChanging(value);
					this.SendPropertyChanging();
					this._LAST_YRQ_ATTND = value;
					this.SendPropertyChanged("LAST_YRQ_ATTND");
					this.OnLAST_YRQ_ATTNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STU_CITY", DbType="VarChar(16)")]
		public string STU_CITY
		{
			get
			{
				return this._STU_CITY;
			}
			set
			{
				if ((this._STU_CITY != value))
				{
					this.OnSTU_CITYChanging(value);
					this.SendPropertyChanging();
					this._STU_CITY = value;
					this.SendPropertyChanged("STU_CITY");
					this.OnSTU_CITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STU_ST", DbType="Char(2)")]
		public string STU_ST
		{
			get
			{
				return this._STU_ST;
			}
			set
			{
				if ((this._STU_ST != value))
				{
					this.OnSTU_STChanging(value);
					this.SendPropertyChanging();
					this._STU_ST = value;
					this.SendPropertyChanged("STU_ST");
					this.OnSTU_STChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STU_STREET", DbType="VarChar(24)")]
		public string STU_STREET
		{
			get
			{
				return this._STU_STREET;
			}
			set
			{
				if ((this._STU_STREET != value))
				{
					this.OnSTU_STREETChanging(value);
					this.SendPropertyChanging();
					this._STU_STREET = value;
					this.SendPropertyChanged("STU_STREET");
					this.OnSTU_STREETChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STU_ZIP", DbType="Char(9)")]
		public string STU_ZIP
		{
			get
			{
				return this._STU_ZIP;
			}
			set
			{
				if ((this._STU_ZIP != value))
				{
					this.OnSTU_ZIPChanging(value);
					this.SendPropertyChanging();
					this._STU_ZIP = value;
					this.SendPropertyChanged("STU_ZIP");
					this.OnSTU_ZIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OPT_1", DbType="Char(1)")]
		public System.Nullable<char> OPT_1
		{
			get
			{
				return this._OPT_1;
			}
			set
			{
				if ((this._OPT_1 != value))
				{
					this.OnOPT_1Changing(value);
					this.SendPropertyChanging();
					this._OPT_1 = value;
					this.SendPropertyChanged("OPT_1");
					this.OnOPT_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OPT_2", DbType="Char(1)")]
		public System.Nullable<char> OPT_2
		{
			get
			{
				return this._OPT_2;
			}
			set
			{
				if ((this._OPT_2 != value))
				{
					this.OnOPT_2Changing(value);
					this.SendPropertyChanging();
					this._OPT_2 = value;
					this.SendPropertyChanged("OPT_2");
					this.OnOPT_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RES_STAT", DbType="Char(1)")]
		public System.Nullable<char> RES_STAT
		{
			get
			{
				return this._RES_STAT;
			}
			set
			{
				if ((this._RES_STAT != value))
				{
					this.OnRES_STATChanging(value);
					this.SendPropertyChanging();
					this._RES_STAT = value;
					this.SendPropertyChanged("RES_STAT");
					this.OnRES_STATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENDER", DbType="Char(1)")]
		public System.Nullable<char> GENDER
		{
			get
			{
				return this._GENDER;
			}
			set
			{
				if ((this._GENDER != value))
				{
					this.OnGENDERChanging(value);
					this.SendPropertyChanging();
					this._GENDER = value;
					this.SendPropertyChanged("GENDER");
					this.OnGENDERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SID", DbType="Char(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SID
		{
			get
			{
				return this._SID;
			}
			set
			{
				if ((this._SID != value))
				{
					this.OnSIDChanging(value);
					this.SendPropertyChanging();
					this._SID = value;
					this.SendPropertyChanged("SID");
					this.OnSIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STU_DAY_PHONE", DbType="Char(10)")]
		public string STU_DAY_PHONE
		{
			get
			{
				return this._STU_DAY_PHONE;
			}
			set
			{
				if ((this._STU_DAY_PHONE != value))
				{
					this.OnSTU_DAY_PHONEChanging(value);
					this.SendPropertyChanging();
					this._STU_DAY_PHONE = value;
					this.SendPropertyChanged("STU_DAY_PHONE");
					this.OnSTU_DAY_PHONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STU_ENR_STAT", DbType="Char(1)")]
		public System.Nullable<char> STU_ENR_STAT
		{
			get
			{
				return this._STU_ENR_STAT;
			}
			set
			{
				if ((this._STU_ENR_STAT != value))
				{
					this.OnSTU_ENR_STATChanging(value);
					this.SendPropertyChanging();
					this._STU_ENR_STAT = value;
					this.SendPropertyChanged("STU_ENR_STAT");
					this.OnSTU_ENR_STATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STU_EVE_PHONE", DbType="Char(10)")]
		public string STU_EVE_PHONE
		{
			get
			{
				return this._STU_EVE_PHONE;
			}
			set
			{
				if ((this._STU_EVE_PHONE != value))
				{
					this.OnSTU_EVE_PHONEChanging(value);
					this.SendPropertyChanging();
					this._STU_EVE_PHONE = value;
					this.SendPropertyChanged("STU_EVE_PHONE");
					this.OnSTU_EVE_PHONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STU_NAME", DbType="VarChar(22)")]
		public string STU_NAME
		{
			get
			{
				return this._STU_NAME;
			}
			set
			{
				if ((this._STU_NAME != value))
				{
					this.OnSTU_NAMEChanging(value);
					this.SendPropertyChanging();
					this._STU_NAME = value;
					this.SendPropertyChanged("STU_NAME");
					this.OnSTU_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STU_TYP", DbType="Char(1)")]
		public System.Nullable<char> STU_TYP
		{
			get
			{
				return this._STU_TYP;
			}
			set
			{
				if ((this._STU_TYP != value))
				{
					this.OnSTU_TYPChanging(value);
					this.SendPropertyChanging();
					this._STU_TYP = value;
					this.SendPropertyChanged("STU_TYP");
					this.OnSTU_TYPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VET_BENE", DbType="Char(1)")]
		public System.Nullable<char> VET_BENE
		{
			get
			{
				return this._VET_BENE;
			}
			set
			{
				if ((this._VET_BENE != value))
				{
					this.OnVET_BENEChanging(value);
					this.SendPropertyChanging();
					this._VET_BENE = value;
					this.SendPropertyChanged("VET_BENE");
					this.OnVET_BENEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BAD_ADDR_CD", DbType="Char(2)")]
		public string BAD_ADDR_CD
		{
			get
			{
				return this._BAD_ADDR_CD;
			}
			set
			{
				if ((this._BAD_ADDR_CD != value))
				{
					this.OnBAD_ADDR_CDChanging(value);
					this.SendPropertyChanging();
					this._BAD_ADDR_CD = value;
					this.SendPropertyChanged("BAD_ADDR_CD");
					this.OnBAD_ADDR_CDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STU_INT", DbType="Char(1)")]
		public System.Nullable<char> STU_INT
		{
			get
			{
				return this._STU_INT;
			}
			set
			{
				if ((this._STU_INT != value))
				{
					this.OnSTU_INTChanging(value);
					this.SendPropertyChanging();
					this._STU_INT = value;
					this.SendPropertyChanged("STU_INT");
					this.OnSTU_INTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STU_PRG_ENR", DbType="Char(4)")]
		public string STU_PRG_ENR
		{
			get
			{
				return this._STU_PRG_ENR;
			}
			set
			{
				if ((this._STU_PRG_ENR != value))
				{
					this.OnSTU_PRG_ENRChanging(value);
					this.SendPropertyChanging();
					this._STU_PRG_ENR = value;
					this.SendPropertyChanged("STU_PRG_ENR");
					this.OnSTU_PRG_ENRChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.YRQ_M")]
	public partial class YRQ_M : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IMAGE_RECNBR;
		
		private string _YRQ;
		
		private string _ABBR_TITLE;
		
		private System.Nullable<System.DateTime> _FIFTH_DAY_YRQ;
		
		private System.Nullable<System.DateTime> _FIRST_DAY_YRQ;
		
		private System.Nullable<decimal> _HDCNT;
		
		private System.Nullable<System.DateTime> _LAST_DAY_YRQ;
		
		private System.Nullable<System.DateTime> _LAST_TEN_UPD;
		
		private System.Nullable<System.DateTime> _TEN_DAY_YRQ;
		
		private System.Nullable<char> _FREEZE_REG;
		
		private System.Nullable<decimal> _REG_MAX_CR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIMAGE_RECNBRChanging(int value);
    partial void OnIMAGE_RECNBRChanged();
    partial void OnYRQChanging(string value);
    partial void OnYRQChanged();
    partial void OnABBR_TITLEChanging(string value);
    partial void OnABBR_TITLEChanged();
    partial void OnFIFTH_DAY_YRQChanging(System.Nullable<System.DateTime> value);
    partial void OnFIFTH_DAY_YRQChanged();
    partial void OnFIRST_DAY_YRQChanging(System.Nullable<System.DateTime> value);
    partial void OnFIRST_DAY_YRQChanged();
    partial void OnHDCNTChanging(System.Nullable<decimal> value);
    partial void OnHDCNTChanged();
    partial void OnLAST_DAY_YRQChanging(System.Nullable<System.DateTime> value);
    partial void OnLAST_DAY_YRQChanged();
    partial void OnLAST_TEN_UPDChanging(System.Nullable<System.DateTime> value);
    partial void OnLAST_TEN_UPDChanged();
    partial void OnTEN_DAY_YRQChanging(System.Nullable<System.DateTime> value);
    partial void OnTEN_DAY_YRQChanged();
    partial void OnFREEZE_REGChanging(System.Nullable<char> value);
    partial void OnFREEZE_REGChanged();
    partial void OnREG_MAX_CRChanging(System.Nullable<decimal> value);
    partial void OnREG_MAX_CRChanged();
    #endregion
		
		public YRQ_M()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMAGE_RECNBR", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int IMAGE_RECNBR
		{
			get
			{
				return this._IMAGE_RECNBR;
			}
			set
			{
				if ((this._IMAGE_RECNBR != value))
				{
					this.OnIMAGE_RECNBRChanging(value);
					this.SendPropertyChanging();
					this._IMAGE_RECNBR = value;
					this.SendPropertyChanged("IMAGE_RECNBR");
					this.OnIMAGE_RECNBRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YRQ", DbType="Char(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string YRQ
		{
			get
			{
				return this._YRQ;
			}
			set
			{
				if ((this._YRQ != value))
				{
					this.OnYRQChanging(value);
					this.SendPropertyChanging();
					this._YRQ = value;
					this.SendPropertyChanged("YRQ");
					this.OnYRQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ABBR_TITLE", DbType="VarChar(10)")]
		public string ABBR_TITLE
		{
			get
			{
				return this._ABBR_TITLE;
			}
			set
			{
				if ((this._ABBR_TITLE != value))
				{
					this.OnABBR_TITLEChanging(value);
					this.SendPropertyChanging();
					this._ABBR_TITLE = value;
					this.SendPropertyChanged("ABBR_TITLE");
					this.OnABBR_TITLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIFTH_DAY_YRQ", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> FIFTH_DAY_YRQ
		{
			get
			{
				return this._FIFTH_DAY_YRQ;
			}
			set
			{
				if ((this._FIFTH_DAY_YRQ != value))
				{
					this.OnFIFTH_DAY_YRQChanging(value);
					this.SendPropertyChanging();
					this._FIFTH_DAY_YRQ = value;
					this.SendPropertyChanged("FIFTH_DAY_YRQ");
					this.OnFIFTH_DAY_YRQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRST_DAY_YRQ", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> FIRST_DAY_YRQ
		{
			get
			{
				return this._FIRST_DAY_YRQ;
			}
			set
			{
				if ((this._FIRST_DAY_YRQ != value))
				{
					this.OnFIRST_DAY_YRQChanging(value);
					this.SendPropertyChanging();
					this._FIRST_DAY_YRQ = value;
					this.SendPropertyChanged("FIRST_DAY_YRQ");
					this.OnFIRST_DAY_YRQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HDCNT", DbType="Decimal(5,0)")]
		public System.Nullable<decimal> HDCNT
		{
			get
			{
				return this._HDCNT;
			}
			set
			{
				if ((this._HDCNT != value))
				{
					this.OnHDCNTChanging(value);
					this.SendPropertyChanging();
					this._HDCNT = value;
					this.SendPropertyChanged("HDCNT");
					this.OnHDCNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_DAY_YRQ", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> LAST_DAY_YRQ
		{
			get
			{
				return this._LAST_DAY_YRQ;
			}
			set
			{
				if ((this._LAST_DAY_YRQ != value))
				{
					this.OnLAST_DAY_YRQChanging(value);
					this.SendPropertyChanging();
					this._LAST_DAY_YRQ = value;
					this.SendPropertyChanged("LAST_DAY_YRQ");
					this.OnLAST_DAY_YRQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_TEN_UPD", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> LAST_TEN_UPD
		{
			get
			{
				return this._LAST_TEN_UPD;
			}
			set
			{
				if ((this._LAST_TEN_UPD != value))
				{
					this.OnLAST_TEN_UPDChanging(value);
					this.SendPropertyChanging();
					this._LAST_TEN_UPD = value;
					this.SendPropertyChanged("LAST_TEN_UPD");
					this.OnLAST_TEN_UPDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_DAY_YRQ", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> TEN_DAY_YRQ
		{
			get
			{
				return this._TEN_DAY_YRQ;
			}
			set
			{
				if ((this._TEN_DAY_YRQ != value))
				{
					this.OnTEN_DAY_YRQChanging(value);
					this.SendPropertyChanging();
					this._TEN_DAY_YRQ = value;
					this.SendPropertyChanged("TEN_DAY_YRQ");
					this.OnTEN_DAY_YRQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FREEZE_REG", DbType="Char(1)")]
		public System.Nullable<char> FREEZE_REG
		{
			get
			{
				return this._FREEZE_REG;
			}
			set
			{
				if ((this._FREEZE_REG != value))
				{
					this.OnFREEZE_REGChanging(value);
					this.SendPropertyChanging();
					this._FREEZE_REG = value;
					this.SendPropertyChanged("FREEZE_REG");
					this.OnFREEZE_REGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REG_MAX_CR", DbType="Decimal(4,1)")]
		public System.Nullable<decimal> REG_MAX_CR
		{
			get
			{
				return this._REG_MAX_CR;
			}
			set
			{
				if ((this._REG_MAX_CR != value))
				{
					this.OnREG_MAX_CRChanging(value);
					this.SendPropertyChanging();
					this._REG_MAX_CR = value;
					this.SendPropertyChanged("REG_MAX_CR");
					this.OnREG_MAX_CRChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
